all:
  hosts:
    node1:
      ansible_host: 10.11.10.2
      ip: 10.11.10.2
    node2:
      ansible_host: 10.11.10.3
      ip: 10.11.10.3
    node3:
      ansible_host: 10.11.10.4
      ip: 10.11.10.4
    node4:
      ansible_host: 10.11.10.20
      ip: 10.11.10.20
    node5:
      ansible_host: 10.11.10.21
      ip: 10.11.10.21
    node6:
      ansible_host: 10.11.10.22
      ip: 10.11.10.22
    node7:
      ansible_host: 10.11.10.50
      ip: 10.11.10.50
    node8:
      ansible_host: 10.11.10.51
      ip: 10.11.10.51
    node9:
      ansible_host: 10.11.10.52
      ip: 10.11.10.52
    node10:
      ansible_host: 10.11.11.2
      ip: 10.11.11.2
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node4:
        node5:
        node6:
        node7:
        node8:
        node9:
        node10:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
    ingress:
      hosts:
        node4:
        node5:
        node6:
      vars:
        node_labels:
          ingress: true
    elasticsearch:
      hosts:
        node7:
        node8:
        node9:
      vars:
        node_labels:
          node-service: elasticsearch
        node_taints:
          - "node-service=elasticsearch:NoSchedule"
    cloud-worker:
      hosts:
        node4:
        node5:
        node6:
      vars:
        node_labels:
          node-type: cloud-worker
        node_taints:
          - "node-type=cloud:NoSchedule"
    cloud-master:
      hosts:
        node1:
        node2:
        node3:
      vars:
        node_labels:
          node-type: cloud-master
