all:
  hosts:
    node1:
      ansible_host: 10.12.10.5
      ip: 10.12.10.5
      access_ip: 10.12.10.5
    node2:
      ansible_host: 10.12.10.3
      ip: 10.12.10.3
      access_ip: 10.12.10.3
    node3:
      ansible_host: 10.12.10.4
      ip: 10.12.10.4
      access_ip: 10.12.10.4
    node4:
      ansible_host: 10.12.10.20
      ip: 10.12.10.20
      access_ip: 10.12.10.20
    node5:
      ansible_host: 10.12.10.21
      ip: 10.12.10.21
      access_ip: 10.12.10.21
    node6:
      ansible_host: 10.12.10.22
      ip: 10.12.10.22
      access_ip: 10.12.10.22
    node7:
      ansible_host: 10.12.10.23
      ip: 10.12.10.23
      access_ip: 10.12.10.23
    node8:
      ansible_host: 10.12.10.24
      ip: 10.12.10.24
      access_ip: 10.12.10.24
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node4:
        node5:
        node6:
        node7:
        node8:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
    cloud-worker:
      hosts:
        node4:
        node5:
        node6:
      vars:
        node_labels:
          node-type: cloud-worker
        node_taints:
          - "node-type=cloud:NoSchedule"
    cloud-worker2:
      hosts:
        node7:
        node8:
      vars:
        node_labels:
          node-type: cloud-worker

    cloud-master:
      hosts:
        node1:
        node2:
        node3:
      vars:
        node_labels:
          node-type: cloud-master
